Cp 92 checklist
hollan2/capstone_project pull request #64
Opened 2023-05-29 02:27 UTC by adamstag20

Added end of level displays for success and fail of each level. Confetti for success. Would need to build new component for mapping more objectives as they come.

2023-05-29 04:50 UTC, hollan2 requested changes
Overall it looks really good! Might consider adding a delay before it pops up so we can see the result to our last round of play. Also, maybe we should list the resources of everyone too in the end card????

2023-05-29 04:50 UTC, hollan2 commented on Isle of Trust/src/components/EndOfLevel.tsx
> +                        <h2 className="text-center"> some Players were unable to pay their mortgage!</h2>
can we make Players lowercase here

2023-05-29 04:50 UTC, hollan2 commented on Isle of Trust/src/components/EndOfLevel.tsx
> +                        <div className="popup-content">
this pop up has scroll bars on each axis which is a little weird. If you can figure out how to remove that, that'd be great but if it's too hard don't worry about it

2023-05-29 04:50 UTC, hollan2 commented on Isle of Trust/src/routes/TutorialGameView.tsx
> +       /* for (let i = 0; i <= checkResource.length; i++){
remove comment

2023-05-29 04:50 UTC, hollan2 commented on Isle of Trust/src/components/EndOfLevel.tsx
>  //TODO: This is a basic set up of the pop up using the logic from the "History" pop up, it still needs content
should we remove these comments?

2023-05-29 04:50 UTC, hollan2 requested changes
Overall it looks really good! Might consider adding a delay before it pops up so we can see the result to our last round of play. Also, maybe we should list the resources of everyone too in the end card????

2023-05-30 21:53 UTC, adamstag20 reviewed
I have updated these changes

2023-05-31 02:58 UTC, hollan2 approved these changes
Looks amazing!!

2023-05-31 03:22 UTC, merged