Update credits and copyright
hollan2/capstone_project pull request #73
Opened 2023-05-31 06:42 UTC by hollan2

Added our names to the credits and updated copyright to 2023

2023-05-31 22:38 UTC, dnghiem02 requested changes
Looks great! Just a super picky point is that you may want to add an "and" before Adam's name for the sake of consistency😅

2023-06-01 07:22 UTC, hollan2 commented
> 

Fixed! Thanks for catching that!

2023-06-01 07:24 UTC, hollan2 commented
> Looks great! Just a super picky point is that you may want to add an "and" before Adam's name for the sake of consistency😅

Fixed! Thanks for catching that!!

2023-06-01 15:39 UTC, dnghiem02 approved these changes

2023-06-01 17:23 UTC, merged